const SKILL_CATALOG = [
  { name: 'JavaScript', aliases: ['javascript', 'js', 'ecmascript'], category: 'frontend' },
  { name: 'TypeScript', aliases: ['typescript', 'ts'], category: 'frontend' },
  { name: 'React', aliases: ['react', 'reactjs', 'react.js'], category: 'frontend' },
  { name: 'Next.js', aliases: ['next.js', 'nextjs'], category: 'frontend' },
  { name: 'Vue', aliases: ['vue', 'vue.js'], category: 'frontend' },
  { name: 'Angular', aliases: ['angular'], category: 'frontend' },
  { name: 'HTML/CSS', aliases: ['html', 'css', 'sass', 'tailwind'], category: 'frontend' },

  { name: 'Node.js', aliases: ['node', 'node.js', 'express', 'nestjs'], category: 'backend' },
  { name: 'Python', aliases: ['python', 'django', 'fastapi', 'flask'], category: 'backend' },
  { name: 'Java', aliases: ['java', 'spring'], category: 'backend' },
  { name: 'C#/.NET', aliases: ['c#', 'dotnet', '.net'], category: 'backend' },
  { name: 'Go', aliases: ['golang', 'go'], category: 'backend' },
  { name: 'SQL', aliases: ['sql', 'postgresql', 'mysql', 'sqlite'], category: 'backend' },
  { name: 'MongoDB', aliases: ['mongodb', 'mongo'], category: 'backend' },
  { name: 'Redis', aliases: ['redis'], category: 'backend' },
  { name: 'GraphQL', aliases: ['graphql'], category: 'backend' },

  { name: 'AWS', aliases: ['aws', 'amazon web services'], category: 'cloud_devops' },
  { name: 'Azure', aliases: ['azure'], category: 'cloud_devops' },
  { name: 'GCP', aliases: ['gcp', 'google cloud'], category: 'cloud_devops' },
  { name: 'Docker', aliases: ['docker', 'containerization'], category: 'cloud_devops' },
  { name: 'Kubernetes', aliases: ['kubernetes', 'k8s'], category: 'cloud_devops' },
  { name: 'CI/CD', aliases: ['ci/cd', 'github actions', 'jenkins', 'gitlab ci'], category: 'cloud_devops' },

  { name: 'TensorFlow', aliases: ['tensorflow'], category: 'ai_ml' },
  { name: 'PyTorch', aliases: ['pytorch'], category: 'ai_ml' },
  { name: 'Machine Learning', aliases: ['machine learning', 'ml'], category: 'ai_ml' },
  { name: 'Data Analysis', aliases: ['data analysis', 'pandas', 'numpy'], category: 'ai_ml' },
  { name: 'NLP', aliases: ['nlp', 'natural language processing'], category: 'ai_ml' },

  { name: 'Figma', aliases: ['figma'], category: 'design' },
  { name: 'UI/UX', aliases: ['ui/ux', 'ux', 'user experience', 'interaction design'], category: 'design' },
  { name: 'Adobe Suite', aliases: ['photoshop', 'illustrator', 'adobe'], category: 'design' },

  { name: 'Product Management', aliases: ['product management', 'roadmap', 'product strategy'], category: 'product' },
  { name: 'Agile', aliases: ['agile', 'scrum', 'kanban'], category: 'product' },
  { name: 'Stakeholder Management', aliases: ['stakeholder management'], category: 'product' },

  { name: 'Communication', aliases: ['communication', 'presentation'], category: 'soft_skills' },
  { name: 'Leadership', aliases: ['leadership', 'mentoring', 'team lead'], category: 'soft_skills' },
  { name: 'Problem Solving', aliases: ['problem solving', 'analytical thinking'], category: 'soft_skills' },
  { name: 'Collaboration', aliases: ['collaboration', 'teamwork'], category: 'soft_skills' },
  { name: 'Time Management', aliases: ['time management', 'prioritization'], category: 'soft_skills' },
];

const INTEREST_KEYWORDS = [
  'open source',
  'hackathon',
  'robotics',
  'web development',
  'data science',
  'ai',
  'machine learning',
  'entrepreneurship',
  'design systems',
  'teaching',
  'mentoring',
  'research',
  'community',
  'volunteering',
  'cybersecurity',
  'product strategy',
  'gaming',
  'content creation',
];

const SUBJECT_KEYWORDS = [
  'computer science',
  'software engineering',
  'data structures',
  'algorithms',
  'database systems',
  'operating systems',
  'computer networks',
  'machine learning',
  'artificial intelligence',
  'statistics',
  'probability',
  'linear algebra',
  'calculus',
  'economics',
  'management',
  'marketing',
  'psychology',
  'human computer interaction',
  'accounting',
  'finance',
];

const TOOL_KEYWORDS = [
  'react',
  'node',
  'express',
  'python',
  'java',
  'c++',
  'sql',
  'mongodb',
  'postgresql',
  'docker',
  'kubernetes',
  'aws',
  'azure',
  'gcp',
  'figma',
  'tableau',
  'power bi',
  'tensorflow',
  'pytorch',
  'git',
  'github',
  'jira',
];

const PROJECT_KEYWORDS = [
  'project',
  'capstone',
  'thesis',
  'prototype',
  'application',
  'dashboard',
  'automation',
  'system',
  'platform',
  'model',
  'internship project',
];

const EDUCATION_KEYWORDS = [
  'bachelor',
  'master',
  'phd',
  'university',
  'college',
  'bootcamp',
  'certification',
  'diploma',
  'degree',
];

const EXPERIENCE_KEYWORDS = [
  'experience',
  'worked',
  'intern',
  'developer',
  'engineer',
  'manager',
  'analyst',
  'consultant',
  'lead',
  'years',
];

const DOMAIN_KEYWORDS = {
  software: ['software', 'web', 'frontend', 'backend', 'full stack', 'application'],
  data: ['data', 'analytics', 'machine learning', 'ml', 'ai', 'statistics'],
  design: ['ux', 'ui', 'design', 'figma', 'prototype'],
  product: ['product', 'roadmap', 'stakeholder', 'strategy'],
  marketing: ['marketing', 'seo', 'growth', 'campaign'],
  business: ['business', 'operations', 'sales', 'finance'],
};

module.exports = {
  SKILL_CATALOG,
  INTEREST_KEYWORDS,
  SUBJECT_KEYWORDS,
  TOOL_KEYWORDS,
  PROJECT_KEYWORDS,
  EDUCATION_KEYWORDS,
  EXPERIENCE_KEYWORDS,
  DOMAIN_KEYWORDS,
};
